[project]
name = "laissez-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "eth-account>=0.13.7",
    "fastmcp>=2.12.3",
    "python-dotenv>=1.1.1",
    "web3>=7.13.0",
    "x402>=0.2.1",
]
